Update createtables.sql
changed the varchar[] to varchar() because of PostgreSQL gives error while inserting a string: 

ERROR:  array value must start with "{" or dimension information